name: My First Action
on: [push] # Запускать при каждом пуше кода

jobs:
  Start-Bot:
    runs-on: ubuntu-latest # Используем сервер GitHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run greeting
        env:
          MY_TOKEN: ${{ secrets.TT_BOT_TOKEN_TEST }} # Мы берем секрет из настроек и кладем в переменную
        run: python tt-ramec-bot-test.py
