name: Test-bot
on: #[push] # Запускать при каждом пуше кода
  schedule:
    # 06:30 UTC = 09:30 MSK, 2 = вторник
    - cron: '00 08 * * *'
      #timezone: 'Europe/Moscow'
  workflow_dispatch:
# Добавляем права на уровне всего файла (перед заданиями)
permissions:
  actions: write
  contents: write
jobs:
  Start-Bot:
    runs-on: ubuntu-latest # Используем сервер GitHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install telebot
        run: pip install pyTelegramBotAPI
      - name: Run greeting
        env:
          MY_TOKEN: ${{ secrets.TT_BOT_TOKEN_TEST }} # Мы берем секрет из настроек и кладем в переменную
        run: python tt-ramec-bot-test.py
      - name: Keepalive
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          echo "Last run: $(date)" > last_run.txt
          git add last_run.txt
          git commit -m "Keepalive update [skip ci]" || echo "No changes to commit"
          git push
