name: TT Post Bot

on:
  schedule:
    # 15:00 UTC = 18:00 MSK, 0 = воскресенье
    - cron: '0 15 * * 0'
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  run-tt-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install pyTelegramBotAPI

      - name: Run TT Bot
        env:
          MY_TOKEN: ${{ secrets.TT_BOT_TOKEN }}
        run: python tt-ramec-bot.py

      #- name: Keepalive Workflow
        #uses: gautamkrishnar/keepalive-workflow@v2
