name: TT Post Bot

on:
  schedule:
    # 15:00 UTC = 18:00 MSK, 0 = воскресенье
    - cron: '0 12 * * 0'
  workflow_dispatch: # Кнопка для ручного запуска
# Добавляем права на уровне всего файла (перед заданиями)
permissions:
  actions: write
  contents: write
jobs:
  run-tt-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install pyTelegramBotAPI

      - name: Run TT Bot
        env:
          MY_TOKEN: ${{ secrets.TT_BOT_TOKEN }}
        run: python tt-ramec-bot.py
      - name: Keepalive
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          echo "Last run: $(date)" > last_run.txt
          git add last_run.txt
          git commit -m "Keepalive update [skip ci]" || echo "No changes to commit"
          git push
